#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'mult_data_0', class 'mult_data'
 * The macros are prefixed with 'MULT_DATA_0_'.
 * The prefix is the slave descriptor.
 */
#define MULT_DATA_0_COMPONENT_TYPE mult_data
#define MULT_DATA_0_COMPONENT_NAME mult_data_0
#define MULT_DATA_0_BASE 0x0
#define MULT_DATA_0_SPAN 64
#define MULT_DATA_0_END 0x3f

/*
 * Macros for device 'mult_control_0', class 'mult_control'
 * The macros are prefixed with 'MULT_CONTROL_0_'.
 * The prefix is the slave descriptor.
 */
#define MULT_CONTROL_0_COMPONENT_TYPE mult_control
#define MULT_CONTROL_0_COMPONENT_NAME mult_control_0
#define MULT_CONTROL_0_BASE 0x40
#define MULT_CONTROL_0_SPAN 64
#define MULT_CONTROL_0_END 0x7f

/*
 * Macros for device 'add_data_0', class 'add_data'
 * The macros are prefixed with 'ADD_DATA_0_'.
 * The prefix is the slave descriptor.
 */
#define ADD_DATA_0_COMPONENT_TYPE add_data
#define ADD_DATA_0_COMPONENT_NAME add_data_0
#define ADD_DATA_0_BASE 0x80
#define ADD_DATA_0_SPAN 32
#define ADD_DATA_0_END 0x9f

/*
 * Macros for device 'add_control_0', class 'add_control'
 * The macros are prefixed with 'ADD_CONTROL_0_'.
 * The prefix is the slave descriptor.
 */
#define ADD_CONTROL_0_COMPONENT_TYPE add_control
#define ADD_CONTROL_0_COMPONENT_NAME add_control_0
#define ADD_CONTROL_0_BASE 0xa0
#define ADD_CONTROL_0_SPAN 32
#define ADD_CONTROL_0_END 0xbf


#endif /* _ALTERA_HPS_0_H_ */
